# Generated by Django 4.0.3 on 2022-03-28 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
        migrations.AddField(
            model_name='poll',
            name='garet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='volentier',
            field=models.BooleanField(default=False),
        ),
    ]
