# Generated by Django 4.0.3 on 2022-03-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_poll_answer_remove_poll_title_poll_garet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='essen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.food'),
        ),
    ]
