# Generated by Django 4.0.3 on 2022-03-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_food_poll_essen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foods',
            field=models.CharField(max_length=100),
        ),
    ]
